### ISSUE TITLE
Add job for moving references to qualifiers

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/DeltaBot#1]
My pywikibot repository has a [script](https://github.com/matejsuchanek/pywikibot-scripts/blob/master/fix_qualifiers.py) to [move snaks in references](https://www.wikidata.org/w/index.php?title=Q28053643&diff=422866855&oldid=420946446) (usually misplaced by users or QuickStatements) to qualifiers. I would like to migrate it to a DeltaBot's job.

And a contrary could also be set up.

**Comment by Pascalco** [comment]
Thanks for this suggestion. 

This perfectly fits the scope of DeltaBot.

**Comment by Pascalco** [comment]
I added the function to move snaks in references to qualifiers (60e179f92af60705c59c64252e0a287f706b8676).

At this time, it requires that the qualifier property has to be explicitly mentioned in the jobs file.
