### ISSUE TITLE
no positive/report for complex constraint

### ISSUE THREAD

**Issue by rwst** [Pascalco/DeltaBot#41]
There are no positives reported at [this report page your bot visited](https://www.wikidata.org/wiki/Wikidata:Database_reports/Complex_constraint_violations/P235#Modified_unique_value_constraint) but running the [query](https://query.wikidata.org/#%23%20Title%3A%20Modified%20unique%20value%20constraint%0A%23%20Complex%20constraint%20from%20%5B%5BProperty%20talk%3AP235%5D%5D%0A%23%20Lists%20items%20having%20the%20same%20value%2C%20except%20if%20both%20statements%20have%20mutual%20%5B%5BProperty%3AP6185%7Ctautomer%20of%26%2332%3B%3Csmall%3E%28P6185%29%3C%2Fsmall%3E%5D%5D%20statements%2C%20see%20discusion%20below.%20Please%20don%27t%20switch%20on%20the%20normal%20unique%20value%20constraint%2C%20use%20this%20instead.%0ASELECT%20DISTINCT%20%3Fitem1%20%3Fitem1Label%20%3Fitem2%20%3Fitem2Label%20%3Fvalue%20%0A%7B%0A%09%3Fitem1%20wdt%3AP235%20%3Fvalue%20.%0A%09%3Fitem2%20wdt%3AP235%20%3Fvalue%20.%0A%20%20%20%20MINUS%20%7B%0A%20%20%20%20%20%20%3Fitem1%20wdt%3AP6185%20%3Fitem2.%0A%20%20%20%20%20%20%3Fitem2%20wdt%3AP6185%20%3Fitem1%0A%20%20%20%20%7D%0A%20%20%20%20MINUS%20%7B%0A%20%20%20%20%20%20%3Fitem1%20wdt%3AP31%20%3Fitem2.%0A%20%20%20%20%7D%0A%20%20%20%20MINUS%20%7B%0A%20%20%20%20%20%20%3Fitem2%20wdt%3AP31%20%3Fitem1.%0A%20%20%20%20%7D%0A%09FILTER%28%20%3Fitem1%20%21%3D%20%3Fitem2%20%26%26%20STR%28%20%3Fitem1%20%29%20%3C%20STR%28%20%3Fitem2%20%29%20%29%20.%0A%09SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%20.%0A%7D%0ALIMIT%201000) directly gives 504 positives. Also most report pages I looked at were visited but have no positives which strikes me as suspicious. Either your bot does not work or has a catch that no one knows.

Please clarify.

**Comment by Pascalco** [comment]
As mentioned in https://www.wikidata.org/wiki/Template:Complex_constraint, the query must have a field ?item. I fixed the complex query definition on P235 accordingly.
